import dress from "./assets/dress.png"
import pants from "./assets/pants.jpg"
import sweater from "./assets/sweater.jpg"
import r1 from "./assets/r1.png"
import r2 from "./assets/r2.png"
import r3 from "./assets/r3.png"
import r4 from "./assets/r4.png"
import r5 from "./assets/r5.png"
import r6 from "./assets/r6.jpg"
import r7 from "./assets/r7.jpg"
import o1 from "./assets/o1.png"
import o2 from "./assets/o2.png"
import o3 from "./assets/o3.png"
import o4 from "./assets/o4.png"
import o5 from "./assets/o5.png"


const Products = [
  { id: 1,
    code: 'w5/44/001', 
    season: 'summer', 
    bestSeller: 'N',
    name: 'Dress', 
    description: 'des is here', 
    colors: 'red',
    sex: 'girl',
    age: '1 : 4 Years',
    category: 'Dress',
    price: 450, 
    img: dress },
  
{ id: 2,
    code: 'w5/44/001', 
    season: 'summer', 
    bestSeller: 'N',
    name: 'Pants', 
    description: 'des is here', 
    colors: 'red',
    sex: 'Unisex',
    age: '1 : 10 Years',
    category: 'Pants',
    price: 600, 
    img: pants },
    
{ id: 3,
    code: 'w5/44/001', 
    season: 'summer', 
    bestSeller: 'N',
    name: 'Sweater', 
    description: 'des is here', 
    colors: 'red',
    sex: 'girl',
    age: '1 : 4 Years',
    category: 'Sweater',
    price: 475, 
    img: sweater },

    { id: 4,
    code: 'w5/44/001', 
    season: 'summer', 
    bestSeller: 'N',
    name: 'Romper', 
    description: 'des is here', 
    colors: 'red',
    sex: 'girl',
    age: '0 : 9 Months',
    category: 'Romper',
    price: 299, 
    img: r1 },

    { id: 5,
    code: 'w5/44/001', 
    season: 'summer', 
    bestSeller: 'N',
    name: 'Romper', 
    description: 'des is here', 
    colors: 'red',
    sex: 'girl',
    age: '0 : 12 Months',
    category: 'Romper',
    price: 500, 
    img: r2 },

    { id: 6,
    code: 'w5/44/001', 
    season: 'summer', 
    bestSeller: 'N',
    name: 'Romper', 
    description: 'des is here', 
    colors: 'red',
    sex: 'girl',
    age: '0 : 12 Months',
    category: 'Romper',
    price: 599, 
    img: r3 },

    { id: 7,
    code: 'w5/44/001', 
    season: 'summer', 
    bestSeller: 'N',
    name: 'Romper', 
    description: 'des is here', 
    colors: 'red',
    sex: 'girl',
    age: '0 : 12 Months',
    category: 'Romper',
    price: 599, 
    img: r4 },

    { id: 8,
    code: 'w5/44/001', 
    season: 'summer', 
    bestSeller: 'N',
    name: 'Romper', 
    description: 'des is here', 
    colors: 'red',
    sex: 'girl',
    age: 'Newborn',
    category: 'Romper',
    price: 399, 
    img: r5 },

    { id: 9,
    code: 'w5/44/001', 
    season: 'summer', 
    bestSeller: 'N',
    name: 'Romper', 
    description: 'des is here', 
    colors: 'red',
    sex: 'girl',
    age: '0 : 12 Months',
    category: 'Romper',
    price: 500, 
    img: r6 },

    { id: 10,
    code: 'w5/44/001', 
    season: 'summer', 
    bestSeller: 'N',
    name: 'Romper', 
    description: 'des is here', 
    colors: 'red',
    sex: 'girl',
    age: '0 : 12 Months',
    category: 'Romper',
    price: 500, 
    img: r7 },

    { id: 11,
    code: 'w5/44/001', 
    season: 'summer', 
    bestSeller: 'N',
    name: 'Outfit', 
    description: 'des is here', 
    colors: 'red',
    sex: 'girl',
    age: '0 : 12 Months',
    category: 'Outfit',
    price: 650, 
    img: o1 },

    { id: 12,
    code: 'w5/44/001', 
    season: 'summer', 
    bestSeller: 'N',
    name: 'Outfit', 
    description: 'des is here', 
    colors: 'red',
    sex: 'girl',
    age: '0 : 12 Months',
    category: 'Outfit',
    price: 550, 
    img: o2 },

    { id: 13,
    code: 'w5/44/001', 
    season: 'summer', 
    bestSeller: 'N',
    name: 'Outfit', 
    description: 'des is here', 
    colors: 'red',
    sex: 'girl',
    age: '1 : 10 Years',
    category: 'Outfit',
    price: 1200, 
    img: o3 },

    { id: 14,
    code: 'w5/44/001', 
    season: 'summer', 
    bestSeller: 'N',
    name: 'Outfit', 
    description: 'des is here', 
    colors: 'red',
    sex: 'girl',
    age: '0 : 12 Months',
    category: 'Outfit',
    price: 699, 
    img: o4 },

    { id: 15,
    code: 'w5/44/001', 
    season: 'summer', 
    bestSeller: 'N',
    name: 'Outfit', 
    description: 'des is here', 
    colors: 'red',
    sex: 'girl',
    age: '0 : 12 Months',
    category: 'Outfit',
    price: 699, 
    img: o5 },

    // { id: 16,
    // code: 'w5/44/001', 
    // season: 'summer', 
    // bestSeller: 'N',
    // name: 'Outfit', 
    // description: 'des is here', 
    // colors: 'red',
    // sex: 'girl',
    // age: '1:4',
    // category: 'Outfit',
    // price: 1200, 
    // img: logo },
  ];


export default Products;